### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by mateutek** [CodeEffect/BoundKeys#3]
Got an error when tried to run it.

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\boundkeys.py", line 347, in run
KeyError: 'object'

**Comment by CodeEffect** [comment]
Hi, can I ask what platform and ST version you're using please? 

Also, how comfortable are you with perhaps bunging some debugging into the file if I give directions? I could email you an updated boundkeys.py file if that would be a better solution for you?

**Comment by mateutek** [comment]
Win 7 64 ST2

Yeah np. I can help you with debug.

**Comment by CodeEffect** [comment]
Cheers, at line 346 add this:
        print(subKeys)
before this:
        for lastPath in subKeys:
            for binding in subKeys[lastPath]["object"]:
                self.bindings[
                    self.prepKey(binding["keys"])
                ].append(subKeys[lastPath]["name"])

Adding that print in should make it dump a ton of data to the console when it's run. Could you run it, grab the data and check it over for anything personal or private (pretty sure there won't be anything in there but worth checking) and paste it up here or email it to steve@codeeffect.co.uk please?

**Comment by CodeEffect** [comment]
Thanks for that, should be fixed in commit: https://github.com/CodeEffect/BoundKeys/commit/99aed4f767e5c9138a79b4632a1fcbb103571a39

Please let me know if you're still having any problems.

**Comment by mateutek** [comment]
Works :)

---

Pozdrawiam
Mateusz Wo¼niak
tel. 508 252 445
gg:5211741

2013/6/2 CodeEffect notifications@github.com
