### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by hced** [CodeEffect/BoundKeys#4]
Using Sublime Text 3 (3033) on OS X. Tried installing the plugin both via Package Control and manually via git, same problem when running List bound keys:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Installed Packages/BoundKeys.sublime-package/boundkeys.py", line 253, in run
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 140: ordinal not in range(128)
```

**Comment by CodeEffect** [comment]
Thanks, I can't get it to error here though, no matter what odd chars I put in my keymap files. If you're comfortable with a little debugging could you possibly open boundkeys.py and on line 252 add in:
                        print(fullPath)
Just above this line:
                        jsonObj = self.jsonify(open(fullPath, "r").read())

Next time you run it it should print the file names as it processes them, the last one it prints will be the file with the odd character in it. If you could possibly post that file up here or email it to steve@codeeffect.co.uk I should be able to reproduce the error and fix. 

If you're not comfortable with editing the python file let me know and I'll ping you an updated boundkeys.py

Thanks very much :)

**Comment by hced** [comment]
Hi, and thanks for a quick reply!

I'd be happy to troubleshoot this. However, I'm struggling with such a mundane task (assumably) of editing the `boundkeys.py` file. It resides in the `BoundKeys.sublime-package` which I'm unable to open (it only opens as a binary). How would I be able to edit this file?

**Comment by CodeEffect** [comment]
That's new I think, the package manager must now be zipping them on the fly.  

If you've got 7zip or winrar or similar installed then just right click on it and extract to a folder. If you unzip it to the packages folder then I'm pretty sure that that one will take priority over your zipped package (just go up one from the "installed packages"  folder and you should see the "packages" folder). Alternatively just download a fresh zip from the github page and unzip it into that packages folder. You need to have a structure like:
Packages / BoundKeys / AllTheFilesGoHere...

**Comment by hced** [comment]
Okay. After adding the `print(fullPath)` line, I get this output when invoking the `List bound keys` command:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Packages/BoundKeys/boundkeys.py", line 254, in run
    jsonObj = self.jsonify(open(fullPath, "r").read())
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 140: ordinal not in range(128)
```

**Comment by CodeEffect** [comment]
It's not printing anything I'm afraid. Perhaps you do need to remove your zipped copy. Could you do that, restart sublime then try again if poss please?

**Comment by hced** [comment]
Whoa, that comment looks rather stupid by me. :) It's the same output...

What I did was:
- I got rid of the Package Control-installed version.
- Downloaded a zip from your Github master called `BoundKeys-master.zip`.
- Unzipped that folder and placed it in my `Packages/` dir
- Removed the -master bit, so that it's called only `BoundKeys`.
- Restarted Sublime Text 3 and verified that the manually installed version shows up allright (check).
- Edited the `boundkeys.py` file according to your instruction.
- Restarted Sublime again.
- Performed the `List bound keys` command …

… and the above (same output as my original message) came up in the console. I apologize for not being that helpful.

**Comment by CodeEffect** [comment]
Heheh, don't worry, I've just realised that it was me being the dipshit all along, sorry!  :)

The debug isn't showing a long list of files as that loop only goes over the default and user files. The default file is in a zip so doesn't hit that code and the user file is right there, plain as day: "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap". 

Anyway, at least we have our culprit! Would you mind either bunging it up here or emailing it over to me please? Is worth checking that there's nothing personal in it that you don't want to share first. I'm pretty sure there won't be but is worth a look

**Comment by hced** [comment]
Cool as butter in the Arctic. I've sent you the `Default (OSX).sublime-keymap` by email.

**Comment by CodeEffect** [comment]
BOSH! After all that it didn't trigger errors on my system anyway. Maybe a mac thing ;P 

File looked fine, all valid utf-8 so I've popped in a commit that _should_ fix the issue. Let me know if it doesn't! (well, and if it does would be good too :)

**Comment by hced** [comment]
+1 for the BOSH! expression! Never heard it before (can I borrow it?)

And another big plus – it now works awfully great! Super, thanks for helping me out and for making this plugin.

**Comment by CodeEffect** [comment]
No worries, TY for taking the time to report the bug and help me de - **bug** it.

Enjoy the BOSH! I snuck "dipshit" in too especially for you, I was hoping you'd enjoy that one as well :)

**Comment by hced** [comment]
Oh I forgot to thank you for that one as well. Although I have a bad habit of mixing up dipshit and deep shit all the time. Must try and remember spelling each one of those properly according to their actual contexts. Maybe I just dropped a new plugin idea for you right there? I couldn't tell. ... or just maybe it's getting time for bed. Anyways.

**Comment by CodeEffect** [comment]
You knew that one already? I'll have to try harder next time!

It certainly is time for bed. Night night

**Comment by afbroman** [comment]
I'm getting a similar error in ST3 (3059) running on OS X 10.9, but it might have a completely different cause.

After adding the `print(fullPath)` line:

```
/Users/afbroman/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap
/Users/afbroman/Library/Application Support/Sublime Text 3/Packages/Default/Default (OSX).sublime-keymap
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/afbroman/Library/Application Support/Sublime Text 3/Packages/BoundKeys/boundkeys.py", line 337, in run
    jsonObj = self.jsonify(open(filePath, "r").read())
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 377: ordinal not in range(128)
```

I'm not sure what's going on here, because the Packages/Default directory doesn't exist. Out of curiosity, I tried copying the default keymap file into a Default directory, and that just wipes out all keybindings.

Andrew
