### ISSUE TITLE
Cannot run: get TypeError 'encoding' is an invalid keyword argument

### ISSUE THREAD

**Issue by tephyr** [CodeEffect/BoundKeys#5]
On Windows 7 64-bit, after installing BoundKeys from Package Control into ST2, running it shows this on the console (and no results appear):

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\boundkeys.py", line 252, in run
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by CodeEffect** [comment]
Heheh, see last issue and last commit :)

I'll put a check in for ST version and only use "encoding" if we're running ST3.... Should be done. Let me know if you're still having problems :)

**Comment by tephyr** [comment]
Plugin was automatically updated, works great.  Thanks!
